INSERT INTO clubs (name, town,country_id) VALUES ('Arena Burgas', 'Burgas', 1);
INSERT INTO clubs (name, town) VALUES ('Arda 2008', 'Kardzhali');
INSERT INTO clubs (name, town) VALUES ('Cherno More - Ticha', 'Varna');
INSERT INTO clubs (name, town) VALUES ('Slavia', 'Sofia');
INSERT INTO clubs (name, town) VALUES ('CSKA', 'Sofia');
INSERT INTO clubs (name, town) VALUES ('Lokomotiv', 'Ruse');
INSERT INTO clubs (name, town) VALUES ('Varna', 'Varna');
INSERT INTO clubs (name, town) VALUES ('Akva Sport', 'Varna');
INSERT INTO clubs (name, town) VALUES ('Komodor', 'Varna');
INSERT INTO clubs (name, town) VALUES ('Levski', 'Sofia');
INSERT INTO clubs (name, town) VALUES ('CDNA 2013', 'Sofia');
INSERT INTO clubs (name, town) VALUES ('Botev', 'Vratsa');
INSERT INTO clubs (name, town) VALUES ('Lokomotiv Nikola Nakov', 'Sofia');
INSERT INTO clubs (name, town) VALUES ('Chernomorets', 'Burgas');
INSERT INTO clubs (name, town) VALUES ('Botev 2000', 'Vratsa');
INSERT INTO clubs (name, town) VALUES ('Neptun', 'Burgas');
